//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrtzSysInfo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PollingRate_DateTime {
            get {
                return ((int)(this["PollingRate_DateTime"]));
            }
            set {
                this["PollingRate_DateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PollingRate_Cpu {
            get {
                return ((int)(this["PollingRate_Cpu"]));
            }
            set {
                this["PollingRate_Cpu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PollingRate_Ram {
            get {
                return ((int)(this["PollingRate_Ram"]));
            }
            set {
                this["PollingRate_Ram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int PollingRate_Drives {
            get {
                return ((int)(this["PollingRate_Drives"]));
            }
            set {
                this["PollingRate_Drives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dddd dd.MM.yyyy")]
        public string Formatting_Date {
            get {
                return ((string)(this["Formatting_Date"]));
            }
            set {
                this["Formatting_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HH:mm")]
        public string Formatting_Time {
            get {
                return ((string)(this["Formatting_Time"]));
            }
            set {
                this["Formatting_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Ui_Top {
            get {
                return ((double)(this["Ui_Top"]));
            }
            set {
                this["Ui_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Ui_Left {
            get {
                return ((double)(this["Ui_Left"]));
            }
            set {
                this["Ui_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int PollingRate_Week {
            get {
                return ((int)(this["PollingRate_Week"]));
            }
            set {
                this["PollingRate_Week"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4089446")]
        public long NetworkUpMaxValue {
            get {
                return ((long)(this["NetworkUpMaxValue"]));
            }
            set {
                this["NetworkUpMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13631488")]
        public long NetworkDownMaxValue {
            get {
                return ((long)(this["NetworkDownMaxValue"]));
            }
            set {
                this["NetworkDownMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PollingRate_Temp {
            get {
                return ((int)(this["PollingRate_Temp"]));
            }
            set {
                this["PollingRate_Temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PollingRate_Network {
            get {
                return ((int)(this["PollingRate_Network"]));
            }
            set {
                this["PollingRate_Network"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SectionVisibility_Network {
            get {
                return ((bool)(this["SectionVisibility_Network"]));
            }
            set {
                this["SectionVisibility_Network"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SectionVisibility_System {
            get {
                return ((bool)(this["SectionVisibility_System"]));
            }
            set {
                this["SectionVisibility_System"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SectionVisibility_Drives {
            get {
                return ((bool)(this["SectionVisibility_Drives"]));
            }
            set {
                this["SectionVisibility_Drives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SectionVisibility_DateTime {
            get {
                return ((bool)(this["SectionVisibility_DateTime"]));
            }
            set {
                this["SectionVisibility_DateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int CpuTempMaxValue {
            get {
                return ((int)(this["CpuTempMaxValue"]));
            }
            set {
                this["CpuTempMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int GpuTempMaxValue {
            get {
                return ((int)(this["GpuTempMaxValue"]));
            }
            set {
                this["GpuTempMaxValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double Ui_Width {
            get {
                return ((double)(this["Ui_Width"]));
            }
            set {
                this["Ui_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int PollingRate_InternalIp {
            get {
                return ((int)(this["PollingRate_InternalIp"]));
            }
            set {
                this["PollingRate_InternalIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600000")]
        public int PollingRate_ExternalIp {
            get {
                return ((int)(this["PollingRate_ExternalIp"]));
            }
            set {
                this["PollingRate_ExternalIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ui_ShowInTaskbar {
            get {
                return ((bool)(this["Ui_ShowInTaskbar"]));
            }
            set {
                this["Ui_ShowInTaskbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ui_ExecuteAtStartup {
            get {
                return ((bool)(this["Ui_ExecuteAtStartup"]));
            }
            set {
                this["Ui_ExecuteAtStartup"] = value;
            }
        }
    }
}
